# Generated by Django 5.2.3 on 2025-06-17 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='description',
            field=models.TextField(default='Usuario registrado con acceso básico a la plataforma. Puede visualizar información pública, pero no realizar acciones administrativas.'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='role',
            name='title',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
