# Generated by Django 5.2.3 on 2025-06-17 22:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_role_description_role_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='role',
            name='title',
        ),
    ]
